version: '3'

services:
  shapes: &shapes
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: shapes_local/diego:v1
    volumes:
      - ./resources:/resources
    env_file:
      - ./.envs/.local/.shapes
    
